variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_subnet_azi1_cidr" {}
variable "public_subnet_azi2_cidr" {}
variable "private_app_subnet_az1_cidr" {}
variable "private_app_subnet_az2_cidr" {}
variable "private_data_subnet_az1_cidr" {}
variable "private_data_subnet_az2_cidr" {}